service: minimal-example

plugins:
  - serverless-esbuild

provider:
  name: aws
  runtime: nodejs18.x

functions:
  validateIsin:
    handler: index.handler
    events:
      - http:
          path: validate-isin/{isin}
          method: get
